### ISSUE TITLE
“有趣”的FOFA查询语句收集计划

### ISSUE THREAD

**Issue by 0xf4n9x** [xiecat/fofax#2]
> 收集一些针对有意思的、不限于红队或者安全的FOFA查询搜集语句。

目前已经收集一部分，详见：[“有趣”的FOFA查询语句收集计划](https://github.com/xiecat/fofax/blob/main/docs/Special_Fofa_Query.md)。

大家有好的或者有意思的查询语句欢迎来此Issue下面贡献，后期会将这些所有的“有趣”的FOFA查询语句整合之fofaX中，让fofaX变得更好玩。

提交格式如下：
````
```yaml
id: fx-2021-01
query: 查询的字符串用于fx="jupyter Unauth" eg:(jupyter Unauth)
rule_name: 规则名称 eg:(jupyter 未授权)
rule_english: jupyter unauthorized
description: 规则描述
author: 作者<邮箱>eg:(becivells)
fofa_query: fofa语句 eg:(body="ipython-main-app" && title="Home Page - Select or create
  a notebook")"
tag:
- 标签1 eg(unauthorized)
- 标签2
source: 语句来源


```
````

提交例子
````
```yaml
id: fx-2021-01
query: jupyter Unauth
rule_name: jupyter 未授权
rule_english: jupyter unauthorized
description: jupyter 适用于科学计算场景。如果没有设置账号密码很容易通过web界面直接托管机器
author: becivells
fofa_query: body="ipython-main-app" && title="Home Page - Select or create  a notebook")"
tag:
- unauthorized
source: 

```
````
